### ISSUE TITLE
libtecla fails to compile.

### ISSUE THREAD

**Issue by balister** [balister/meta-sdr#12]
This might be a parallel make issue. I can work around with some incantation of cleansstate and/or just restarting the build.

'''
make[1]: Entering directory '/home/balister/src/oe-core/build/tmp-glibc/work/armv7ahf-vfp-neon-oe-linux-gnueabi/libtecla/1.6.2-r0/libtecla'
mkdir normal_obj
cp ./keytab.h normal_obj/keytab.h
arm-oe-linux-gnueabi-gcc  -march=armv7-a -mfloat-abi=hard -mfpu=neon --sysroot=/home/balister/src/oe-core/build/tmp-glibc/sysroots/ettus-e300 -c -O  -DPACKAGE_NAME="" -DPACKAGE_TARNAME="" -DPACKAGE_VERSION="" -DPACKAGE_STRING="" -DPACKAGE_BUGREPORT="" -DPACKAGE_URL="" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DUSE_TERMINFO=1 -DHAVE_CURSES_H=1 -DHAVE_TERM_H=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_SELECT=1 -DHAVE_SYSV_PTY=1 -D_SVID_SOURCE -D_BSD_SOURCE  -O2 -pipe -g -feliminate-unused-debug-types -fpic -o normal_obj/freelist.o ./freelist.c
mkdir reentrant_obj
cp ./keytab.h reentrant_obj/keytab.h
cp: cannot create regular file 'reentrant_obj/keytab.h': No such file or directory
Makefile.rules:169: recipe for target 'reentrant_obj/keytab.h' failed
make[1]: **\* [reentrant_obj/keytab.h] Error 1
make[1]: **\* Waiting for unfinished jobs....
'''

**Comment by jynik** [comment]
It looks like you worked around this in aed27ae55c797f9e66b6441915cea99dfbc77dc1 for the time being.

I'll take a look soon, given that this is used only by the bladeRF-cli program... adding problems to you plate is rather rude of me, I'm sorry. :( 

I had seen something similar and thought it was addressed with one of the patches included, sorry.  If this become too much of a pain in the butt, I'll probably just add support for libeditline so we can  drop this dependency. Otherwise, once I get it fixed and cleaned up, I suppose it's best to submit a pull request for a more related upstream OE repo, and get it out of the meta-sdr layer.

At any rate, if tecla builds become a persistent pain in the butt, feel free to drop it until I provide something more functional. It's just an optional "nice to have" for the bladeRF-cli. The bladeRF-related build should fallback to an alternate implementation if libtecla is not available.

**Comment by balister** [comment]
I am going to delete this recipe unless someone speaks up about Blade support soon.

**Comment by jynik** [comment]
Kill it with fire, I say.

Looks like Nuand migrated to libedit anyway.

https://github.com/Nuand/bladeRF/commit/f4228d2f9f80a873575206dc20d19ca05060efd8
